import AddPost from '@/components/UiForm/AddPost';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Voom Posts | Create new Post",
    description: "Generated by create next app",
};

const page = () => {

    return (
        <>
            <h2 className='text-2xl text-center text-white'>Add New Post</h2>
            <AddPost />
        </>
    )
}

export default page
