import EditPost from '@/components/UiForm/EditPost';
import { Metadata } from 'next';
import React from 'react'

type props = {
    params: {
        id: string
    }
}

export async function generateMetadata({ params }: props): Promise<Metadata> {
    return {
        title: `Voom Posts | Post #${params.id}`,
        description: "Generated by create next app",
    }
}

const page = ({ params }: props) => {
    return (
        <>
            <h2 className='text-2xl text-center text-white'>Edit Post number {params.id}</h2>
            <EditPost />
        </>
    )
}

export default page
