import { Metadata } from "next";
import Register from "@/components/UiForm/Register";

export const metadata: Metadata = {
    title: "Voom Posts | Register",
    description: "Generated by create next app",
};


const page = () => {
    return (
        <>
            <h2 className='text-2xl text-center text-white'>Register</h2>
            <Register />
        </>
    )
}

export default page
