import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Voom Posts | Create new Post",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            create
        </div>
    )
}

export default page
