import Login from "@/components/UiForm/Login";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Voom Posts | Login",
    description: "Generated by create next app",
};

const Page = () => {

    return (
        <>
            <h2 className='text-2xl text-center text-white'>Login</h2>
            <Login />
        </>
    )
}

export default Page
