import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Voom Posts | Homepage",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            homepage
        </div>
    )
}

export default page
