import Pagination from "@/components/Pagination/Pagination";
import Posts from "@/components/Posts/Posts";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Voom Posts | Homepage",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div className="custom-container pb-5 pt-10">
            <div className="flex flex-col gap-7">
                <Posts />
                <Pagination />
            </div>
        </div>
    )
}

export default page
